### ISSUE TITLE
Add more effects

### ISSUE THREAD

**Issue by uRandomAlex** [timmyws/ULX-RTD#5]
I don't know Lua, but I has finded my old server files with old RTD addon, that has some more effects than yours. Please, add this effects: 
slay
slap
nothing
ignite
explode
take all weapons (except the default loadout (crowbar and other) for TTT).
Here is slap source code:
	
	RESULT.Name = "Slap"
	
	SLAP_SOUNDS = {
		"physics/body/body_medium_impact_hard1.wav",
		"physics/body/body_medium_impact_hard2.wav",
		"physics/body/body_medium_impact_hard3.wav",
		"physics/body/body_medium_impact_hard5.wav",
		"physics/body/body_medium_impact_hard6.wav",
		"physics/body/body_medium_impact_soft5.wav",
		"physics/body/body_medium_impact_soft6.wav",
		"physics/body/body_medium_impact_soft7.wav"
	}
	
	for k, v in pairs (SLAP_SOUNDS) do
		util.PrecacheSound(v)
	end
	
	function RESULT:Trigger(ply)
		ply:EmitSound(SLAP_SOUNDS[math.random(1, #SLAP_SOUNDS)])
		ply:SetLocalVelocity(Vector(math.random(0, 2500), math.random(0, 2500), 2500))
	end
	
	function RESULT:ShowMessage(ply)
		RTD:BroadcastMessageAboutPlayer(ply, "has been ", Color(0, 0, 255), "slapped hard", color_white, "!")
	end

And this is explode source code:
	
	RESULT.Name = "Explode"
	
	function RESULT:Trigger(ply)
		local eff = EffectData()
		eff:SetStart(ply:GetPos())
		eff:SetOrigin(ply:GetPos())
		eff:SetScale(3)
		util.Effect("HelicopterMegaBomb", eff)
		
		ply:EmitSound("ambient/explosions/explode_1.wav")
		ply:Kill()
	end
	
	function RESULT:ShowMessage(ply)
		RTD:BroadcastMessageAboutPlayer(ply, "has ", Color(255, 0, 0), "exploded", color_white, "!")
	end
	
I'm sure that others effects won't be hard to implement.

**Comment by timmyws** [comment]
Ignite is called "spontaneous combustion".
Rocket already explodes the player (after flying him up in the air).

I will add the other ones though. Thanks for the suggestions!
